### ISSUE TITLE
Milestone 2 Scripts To-Do List

### ISSUE THREAD

**Issue by andrealee011** [UBC-MDS/DSCI_522_Group411#25]
- [x] Script 1: download data
- [x] Script 2: wrangle and split data
- [x] Script 3: create and save EDA figures
- [x] Script 4.1: perform hypothesis analysis and save results as figures
- [x] Script 4.2: perform multicollinearity analysis and save results as figures (Ryan)
- [x] Script 4.3: perform ML analysis and save results as figures (Katie)
- [x] Script 5: create final report (Andrea)
- [x] Complete citations `.bib` file for all R and Python packages
- [x] Reference citations in relevant documents
- [x] Add Python package dependencies to README
- [x] Create a run-all script and update README on how to use
