### ISSUE TITLE
Plan for milestone 3

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI_522_Group411#42]
Priorities:
- [x] - make Makefile to run through all analyses (Ryan)
- [x] - edit the data wrangling script to change month to season and region to lat/long (Andrea)
- [x] - update analysis with new variables and rerun scripts (all)
- [x] - rerun analyses with modified dataset (for hypothesis test, multicollinearilty, EDA, and random forest regression) (all) 
- [x] - train models to compare with random forest regression - i.e. linear regression and SVR (Katie, Ryan check over)
- [x]  - make stronger conclusion (andrea)
- [x]  - give motivation for research in an introduction (andrea)

Nice to haves:
- [x] - add tests to scripts!!! (all) - tiffany says our tests are sufficient...
- [x] - figure out better way of reporting error for regression models (take average of cross validation scores?) (Katie, Ryan check over)
- [x]  - fix tables to be csv files formatted with kables (all)
- [x] - address project feedback about report aesthetics (including moving around stuff in report) (All of us, but fix respective sections based on feedback)
- [x]  - fix residual plot (andrea)
- [ ]  - add line to show trend of feature importance plot (see if it looks ok)
- [ ]  - come up with catchy title
- [ ]  - add table of contents (can only add if we change output from github doc to html)
