### ISSUE TITLE
Plan for milestone 4

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI_522_Group411#58]
Katie
-----

- [x] Fix figure 4 (switch x and y axes, use human-readable names)
- [x] Fix figure 1 in the EDA so it becomes 3 different figures - look into ridge plots, switch x and y axes for boxplot
- [x] Test model on test data and report score

Andrea
-------
- [x] Reduce size of figure 2
- [x] Fix EDA Rscript to reflect changes in EDA Rmd and add faceting
- [x] delete saving kables

Ryan
-----
- [x] Change values in tables to 2 sig figs
- [x] Upload Dockerfile that we worked on in lab
- [x] Create makefile2graph (dependency graph on docker hub)

All
---
- [x] Make figure captions more informative
- [x] Each build docker image and ensure it works on our own computers

**Comment by katieb1** [comment]
all done!
